git:
  submodules: false

virtualenv:
  system_site_packages: true

#os:
#  - linux
#  - osx

language: python

python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip --version
  - mkdir ~/.cloudmesh
  - mkdir -p github/cloudmesh
  - cd github/cloudmesh
  - git clone https://github.com/cloudmesh/base.git
  - git clone https://github.com/cloudmesh/client.git
  - cd base
  - pip install -r requirements.txt
  - pip install .
  - cd ../client
  - pip install -r requirements.txt
  - pip install -r requirements-doc.txt
  - pip install .
  - ln -s `pwd` $(dirname `which python`)/../lib/python2.7/site-packages/cloudmesh_client

script:
  - nosetests -v --nocapture tests/test_model.py
  - nosetests -v --nocapture tests/test_pass.py
  - nosetests -v --nocapture tests/test_configdict.py
  - make doc
  - cm help
