git:
  submodules: false

os:
  - linux
  - osx

language: python

python:
  - "2.7"

install:
  - pip install --upgrade pip
  - pip --version
  - mkdir ~/.cloudmesh
  - mkdir -p github/cloudmesh
  - cd github/cloudmesh
  - git clone https://github.com/cloudmesh/base.git
  - git clone https://github.com/cloudmesh/client.git
  - cd base
  - pip install -r requirements.txt
  - python setup.py install
  - cd ../client
  - pip install -r requirements.txt
  - python setup.py install
  - pip install -r requirements-doc.txt
  - make doc

script:
#  - cm help
  - nosetests -v --nocapture tests/test_model.py
  - nosetests -v --nocapture tests/test_pass.py